require_relative '../node_modules/react-native/scripts/react_native_pods'

# ----------------------------------------------------------------
# set this to false to use the compile NotifeeCore framework
# with this set to false this will be the same way the user would consume NotifeeCore framework
# Note: you must pod install after changing this value

$NotifeeCoreFromSources = true
$NotifeeExtension = true

# ----------------------------------------------------------------

platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

project 'testing.xcodeproj'

target 'testing' do
  config = use_native_modules!

  use_react_native!(
    :path => "../node_modules/react-native",
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  if defined?($NotifeeCoreFromSources) && $NotifeeCoreFromSources == true
    pod 'NotifeeCore', :path => "../../ios"
  end
end

target 'NotifeeTestingNSE' do
  pod 'RNNotifeeCore', :path => "../../packages/react-native"
end

pre_install do |installer|
  # Set Swift version on the app target BEFORE validation (required for RCTSwiftUI)
  installer.aggregate_targets.each do |target|
    target.user_project.targets.each do |app_target|
      app_target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '6.0'
      end
    end
    target.user_project.save
  end
end

post_install do |installer|
  react_native_post_install(installer)

  # Re-apply Swift version after install (ensures persistence)
  installer.aggregate_targets.each do |target|
    target.user_project.targets.each do |app_target|
      app_target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '6.0'
      end
    end
    target.user_project.save
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '6.0'
    end

    # Turn off warnings on non-Notifee dependencies - some like libevent are really really noisy
    if !target.name.include? "Notifee"
      target.build_configurations.each do |config|
        config.build_settings["GCC_WARN_INHIBIT_ALL_WARNINGS"] = "YES"
      end
    end
  end
end
